### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ventie30** [angeloocana/gatsby-plugin-i18n#6] opened 2017-10-22 09:01 UTC
Hy guys, I'm struggling a bit after installing this plugin into my test site. I admit that I'm fairly new to Gatsby and I'm still learning how gatsby-config and gatsby-node work. To get started I pick the "gatsby-starter-default" starter, and I played on that.

After in stalling gatsby-plugin-i18n, anytime I run gatsby develop I get this stack trace: 

success delete html files from previous builds — 0.012 s
success open and validate gatsby-config.js — 0.015 s
success copy gatsby files — 0.091 s
success onPreBootstrap — 0.015 s
error UNHANDLED EXCEPTION

  TypeError: Cannot read property 'split' of undefined
  
  - index.js:99 
    [ventie30-react-gatsby]/[ptz-i18n]/dist/index.js:99:26
  
  - _curryN.js:37 
    [ventie30-react-gatsby]/[ramda]/src/internal/_curryN.js:37:27
  
  - _arity.js:6 
    [ventie30-react-gatsby]/[ramda]/src/internal/_arity.js:6:49
  
  - onCreateNode.js:35 Object.onCreateNode
    [ventie30-react-gatsby]/[gatsby-plugin-i18n]/onCreateNode.js:35:52
  
  - api-runner-node.js:104 runAPI
    [ventie30-react-gatsby]/[gatsby]/dist/utils/api-runner-node.js:104:36
  
  - api-runner-node.js:178 
    [ventie30-react-gatsby]/[gatsby]/dist/utils/api-runner-node.js:178:33
  
  - map.js:27 
    [ventie30-react-gatsby]/[async]/internal/map.js:27:9
  
  - eachOfLimit.js:64 replenish
    [ventie30-react-gatsby]/[async]/internal/eachOfLimit.js:64:17
  
  - eachOfLimit.js:49 iterateeCallback
    [ventie30-react-gatsby]/[async]/internal/eachOfLimit.js:49:17
  
  - onlyOnce.js:12 
    [ventie30-react-gatsby]/[async]/internal/onlyOnce.js:12:16
  
  - map.js:29 
    [ventie30-react-gatsby]/[async]/internal/map.js:29:13
  
  - util.js:16 tryCatcher
    [ventie30-react-gatsby]/[bluebird]/js/release/util.js:16:23
  
  - nodeify.js:23 Promise.successAdapter
    [ventie30-react-gatsby]/[bluebird]/js/release/nodeify.js:23:30
  
  - promise.js:566 Promise._settlePromise
    [ventie30-react-gatsby]/[bluebird]/js/release/promise.js:566:21
  
  - promise.js:606 Promise._settlePromiseCtx
    [ventie30-react-gatsby]/[bluebird]/js/release/promise.js:606:10
  
  - async.js:138 Async._drainQueue
    [ventie30-react-gatsby]/[bluebird]/js/release/async.js:138:12
  
  - async.js:143 Async._drainQueues
    [ventie30-react-gatsby]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [ventie30-react-gatsby]/[bluebird]/js/release/async.js:17:14

**This is how my gatsby-config looks like:**

module.exports = {
  siteMetadata: {
    title: "Gatsby Default Starter",
  },
  plugins: [
      "gatsby-plugin-react-helmet",
      {
          resolve: "gatsby-source-filesystem",
          options: {
              name: "posts",
              path: `${__dirname}/content`
          }
      },
      {
          resolve: "gatsby-transformer-remark",
          options: {
              plugins: [
                  {
                      resolve: "gatsby-remark-images",
                      options: {
                          maxWidth: 1200
                      }
                  },
                  {
                      resolve: "gatsby-remark-responsive-iframe"
                  },
                  "gatsby-remark-prismjs",
                  "gatsby-remark-copy-linked-files",
                  "gatsby-remark-autolink-headers"
              ]
          }
      },
      {
        resolve: 'gatsby-plugin-i18n',
        options: {
          langKeyDefault: 'en',
          useLangKeyLayout: false,
          markdownRemark: {
            postPage: 'src/templates/post.jsx',
            query: `
              {
                  allMarkdownRemark {
                      edges {
                      node {
                          fields {
                          slug,
                          langKey
                          }
                      }
                      }
                  }
              }
              `
          }
        }
      },
  ],
}

**And yet this is my gatsby-node:**

const path = require("path");
const _ = require("lodash");
const webpackLodashPlugin = require("lodash-webpack-plugin");

const postNodes = [];

function addSibilingNodes(boundActionCreators) {
    const { createNodeField } = boundActionCreators;
    for (let i = 0; i < postNodes.length; i += 1) {
        const nextID = i + 1 < postNodes.length ? i + 1 : 0;
        const prevID = i - 1 > 0 ? i - 1 : postNodes.length - 1;
        const currNode = postNodes[i];
        const nextNode = postNodes[nextID];
        const prevNode = postNodes[prevID];
        createNodeField({
            node: currNode,
            name: "nextTitle",
            value: nextNode.frontmatter.title
        });
        createNodeField({
            node: currNode,
            name: "nextSlug",
            value: nextNode.fields.slug
        });
        createNodeField({
            node: currNode,
            name: "prevTitle",
            value: prevNode.frontmatter.title
        });
        createNodeField({
            node: currNode,
            name: "prevSlug",
            value: prevNode.fields.slug
        });
    }
}

exports.onCreateNode = ({ node, boundActionCreators, getNode }) => {
    const { createNodeField } = boundActionCreators;
    let slug;
    if (node.internal.type === "MarkdownRemark") {
        const fileNode = getNode(node.parent);
        const parsedFilePath = path.parse(fileNode.relativePath);
        if (
            Object.prototype.hasOwnProperty.call(node, "frontmatter") &&
            Object.prototype.hasOwnProperty.call(node.frontmatter, "slug")
        ) {
            slug = `/${_.kebabCase(node.frontmatter.slug)}`;
        }
        if (
            Object.prototype.hasOwnProperty.call(node, "frontmatter") &&
            Object.prototype.hasOwnProperty.call(node.frontmatter, "title")
        ) {
            slug = `/${_.kebabCase(node.frontmatter.title)}`;
        } else if (parsedFilePath.name !== "index" && parsedFilePath.dir !== "") {
            slug = `/${parsedFilePath.dir}/${parsedFilePath.name}/`;
        } else if (parsedFilePath.dir === "") {
            slug = `/${parsedFilePath.name}/`;
        } else {
            slug = `/${parsedFilePath.dir}/`;
        }
        createNodeField({ node, name: "slug", value: slug });
        postNodes.push(node);
    }

    addSibilingNodes(boundActionCreators);
};

exports.createPages = ({ graphql, boundActionCreators }) => {
    const { createPage } = boundActionCreators;

    return new Promise((resolve, reject) => {
        const postPage = path.resolve("src/templates/post.jsx");
        const tagPage = path.resolve("src/templates/tag.jsx");
        const categoryPage = path.resolve("src/templates/category.jsx");
        resolve(
            graphql(
                `
        {
          allMarkdownRemark {
            edges {
              node {
                frontmatter {
                  tags
                  category
                }
                fields {
                  slug
                }
              }
            }
          }
        }
      `
            ).then(result => {
                if (result.errors) {
                  /* eslint no-console: "off"*/
                    console.log(result.errors);
                    reject(result.errors);
                }

                const tagSet = new Set();
                const categorySet = new Set();
                result.data.allMarkdownRemark.edges.forEach(edge => {
                    if (edge.node.frontmatter.tags) {
                        edge.node.frontmatter.tags.forEach(tag => {
                            tagSet.add(tag);
                        });
                    }

                    if (edge.node.frontmatter.category) {
                        categorySet.add(edge.node.frontmatter.category);
                    }

                    createPage({
                        path: edge.node.fields.slug,
                        component: postPage,
                        context: {
                            slug: edge.node.fields.slug
                        }
                    });
                });

                const tagList = Array.from(tagSet);
                tagList.forEach(tag => {
                    createPage({
                        path: `/tags/${_.kebabCase(tag)}/`,
                        component: tagPage,
                        context: {
                            tag
                        }
                    });
                });

                const categoryList = Array.from(categorySet);
                categoryList.forEach(category => {
                    createPage({
                        path: `/categories/${_.kebabCase(category)}/`,
                        component: categoryPage,
                        context: {
                            category
                        }
                    });
                });
            })
        );
    });
};

exports.modifyWebpackConfig = ({ config, stage }) => {
    if (stage === "build-javascript") {
        config.plugin("Lodash", webpackLodashPlugin, null);
    }
};

I haven't created yet any content in any lang, so my md files are still the same as before, no .lang.md or .lang.js, not sure if that can be anyhow an issue.

**These are the dependencies I have so far:**

"dependencies": {
    "babel-plugin-lodash": "^3.2.11",
    "gatsby": "^1.6.5",
    "gatsby-link": "^1.6.5",
    "gatsby-plugin-i18n": "^0.3.3",
    "gatsby-plugin-react-helmet": "^1.0.1",
    "gatsby-plugin-sharp": "^1.6.0",
    "gatsby-remark-autolink-headers": "^1.4.1",
    "gatsby-remark-copy-linked-files": "^1.5.0",
    "gatsby-remark-images": "^1.5.0",
    "gatsby-remark-prismjs": "^1.2.0",
    "gatsby-remark-responsive-iframe": "^1.4.1",
    "gatsby-source-filesystem": "^1.4.1",
    "gatsby-transformer-remark": "^1.6.3",
    "intl": "^1.2.5",
    "lodash": "^4.17.4",
    "lodash-webpack-plugin": "^0.11.4",
    "purecss": "^1.0.0",
    "react-intl": "^2.4.0",
    "react-owl-carousel": "^2.2.0"
  }

I wasn't planning on using intl or react-intl, but I added them after playing with the i18n demo.
Any idea on how can I debug this?

Thanks in advance for your time.

Luca

**Comment by rudasn** [comment] 2017-11-08 12:39
@angeloocana I believe the issue is at the `ptz-i18n` package where `getSlugAndLang` assumes that all paths (`fileAbsolutePath`) passed to that function are under `/pages/`. See `ptz-i18n/src/index.js#71`.

In my case, I have a `src/content` folder that contains markdown files and `getSlugAndLang` parses those paths as well. Since they are not under `/src/pages/` the `filePath` variable is `undefined` and the following line `const fileName = filePath.split('.');` throws an error.

Does that make sense? Could this be the issue?

**Comment by angeloocana** [comment] 2017-11-08 15:21
Hi @rudasn 

You are right!

Are you using `gatsby-source-filesystem` to add the folder `src/content`?
We need to figure out how to get the folders from `gatsby-source-filesystem`...

I'll be trying to fix it today, Do you have any suggestion?

**Comment by rudasn** [comment] 2017-11-08 18:17
Yes I'm using `gatsby-source-filesystem` for that.

A quick and dirty solution was to change `var filePath = fileAbsolutePath.split('/pages')[1];` to `var filePath = '/' + fileAbsolutePath.split('/src/')[1].split('/').slice(1).join('/');` which is like `/src/*/`.

It may be worth noting that this does not happen when creating pages but when creating nodes (`onCreateNode.js#29`), since `onCreatePage` checks if the path contains the `/pages/` path (`onCreatePage.js#11`).

Definitely worth noting is that I'm very new to gatsby (just started looking at it yesterday) so I really don't know exactly how the whole thing works and if it is really possible to have pieces of markdown being translated and having that work properly.

**Comment by angeloocana** [comment] 2017-11-10 02:04
Sorry @rudasn =( I did not have time to solve it yet =(
I'll be working on it soon, I hope tomorrow.

**Comment by Bouncey** [comment] 2017-11-11 22:59
Subscribing. Would love a fix.

Perhaps using plugin options would help with this, like with `gatsby-source-filesystem` you could pass the plugin the path of your content.

**Comment by Bouncey** [comment] 2017-11-13 23:48
The update to `ptz-i18n` helped move us along, but we are still bound to `pages` [here](https://github.com/angeloocana/gatsby-plugin-i18n/blob/bd70fc3c52279f8c84006a7586769ef103486c76/src/onCreatePage.js#L11) and [here](https://github.com/angeloocana/gatsby-plugin-i18n/blob/e305ebf7c0d33305ece5aa70e5b981ff844d4f74/src/onCreateNode.js#L19).

We need to decouple these or we get graphql errors about `allMarkdownRemark` being missing on the `RootQueryType`

**Comment by Bouncey** [comment] 2017-11-14 12:46
@angeloocana 
Perhaps we can add another condition, like
```js
if (
  node.internal.type === 'File' &&
  (
    node.absolutePath.indexOf('/pages/') > 0 ||
    // regex for 'anyLengthFileName.en.md' or 
    // 'anyLengthFileName.en.jsx'
    (/\w+?\.\w\w\.\w\w\w?$/).test(node.base)
  )
)) {
  // do stuff
}
```

`node.base` is the file name including the extension IIRC. The test for `filename.${langTag}.js` would be a good indicator that we have a file node of a page

**Comment by Bouncey** [comment] 2017-11-14 13:03
This could be a quick patch until a path option is implemented

**Comment by angeloocana** [comment] 2017-11-14 15:30
Hi @Bouncey ,

Thank you for your help!

I liked the regx, I think we should move it to a function called `isInPaths(pluginOptions, path)` and use it in all the places you pointed out. In this way we are free to change the implementation details.

What do you think?

**Comment by sedubois** [comment] 2017-11-14 19:46
+1 🙂

**Comment by angeloocana** [comment] 2017-11-18 00:58
Fixed with version v0.4.0!

Now you can add pagesPaths to gatsby-config:
```
 plugins:{
   //... other plugins
   resolve: 'gatsby-plugin-i18n',
     options: {        
       //.. other options
       pagesPaths: [ '/my/custom/pages/folder1', /my/custom/pages/folder2/ ]
 }
```

Is it working for you guys?

**Comment by sedubois** [comment] 2017-11-19 08:25
Thanks! I just upgraded and used `pagesPaths: [ '/src/pages' ]` with no regression. Next I'll need to uncomment all my blog code to see if it gets pulled in correctly.

**Comment by sedubois** [comment] 2017-11-21 15:37
I'm trying to enable my blog code, but I get `Error: A plugin tried to update a node field that it doesn't own`. My blog code is inspired from gatsbyjs.org, so this error is thrown in gatsby-node.js code equivalent to [this place](https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js#L141) where it tries to add a field `slug` to that node.

The problematic node indeed has a flag `internal.fieldOwners.slug = 'gatsby-plugin-i18n'`, I guess this explains the error. If I understood right, the question is then why `gatsby-plugin-i18n` created a slug field on some nodes even though I didn't ask that (and it's not documented in its API).

If `gatsby-plugin-i18n` internally needs to create some fields to do its magic, could it use some name which won't conflict with other usages, such as `__gatsbyPluginI18n_slug` or something? And can it be explained somewhere what that field is needed for? 

Thanks a lot

**Comment by sedubois** [comment] 2017-11-21 16:57
I could actually just avoid creating the field myself, as the plugin does it, but the problem is that the plugin doesn't create the slug in the same way, the `'/blog'` prefix is missing.

**Comment by sedubois** [comment] 2017-11-22 09:06
OK, I got rid of the issue by actually structuring the code as done in angeloocana.com. So right now I can't say if the changes for this issue worked or not.

**Comment by sedubois** [comment] 2017-11-22 09:09
However, the proper fix for this bug shouldn't be to have to add a `pagesPath` config param to `gatsby-plugin-i18n`, because this duplicates the role of the `gatsby-source-filesystem`. I guess the plugin should instead somehow detect what are the available sources and read from there.

**Comment by angeloocana** [comment] 2017-11-22 15:23
@sedubois 
So you are not using a custom folder anymore?

I agree with you, I would like a way of using `gatsby-source-filesystem` config,
but It is good to have this prop because maybe you don`t want i18n for everything.

**Comment by sedubois** [comment] 2017-11-22 16:43
Currently I have put everything in `src/pages`, yes. I'll come back to this after I have actually managed to publish the blog.

**Closed** 2017-12-03 20:54 UTC
