### ISSUE TITLE
How to handle if the Translation page is not created

### ISSUE THREAD

**Issue by Necmttn** [angeloocana/gatsby-plugin-i18n#22] opened 2017-12-23 13:53 UTC
let's say we have multiple pages which have translations for both, 
but let say one-page haven't translated 
when the user is in `example.en.js` 
switch the language to `ZH` on built version it redirects to 404. is there any way to catch this when the path is not defined. instead of navigating there fire an action etc. etc.  ?

**Comment by sedubois** [comment] 2017-12-23 15:03
This is a duplicate of #18

**Closed** 2017-12-23 15:19 UTC
